### ISSUE TITLE
Todo for main repo

### ISSUE THREAD

**Issue by nschonni** [nschonni/wet-boew#5]
v3.0: single selector roots with % placholders and extends for all SCSS
- [x] GCWU theme
- [x] Intranet theme
- [x] CLF2 theme
- [ ] grids
- [x] Base SCSS

master: single selector roots with % placholders and extends for all SCSS
- [x] Base theme
- [ ] Wet theme
- [ ] verify GCWU theme
- [ ] verify Intranet theme
- [ ] verify CLF2 theme
- [ ] grids

Others:
- [ ] Replace gradient images with gradient mixins
- [ ] .span-1, .span-2, .span-3, .span-4, .span-5, .span-6, .span-7, .span-8, .span-9, .span-10, .span-11, .span-12 and class*=span- selctors to enumerator. 
- [ ] rename variables for readability in pe-ap.js, ex "r"
- [ ] inline var _menu = $(this).closest('li');
- [ ] default-print #base-date-mod {
  float: right;
  display: inline; //inline is ignore
  }
- [ ] consolidate #000 classes in tabbedinterfaces
- [ ] look at "monster" placeholder 
- [ ] Add placeholders to src/js/sass/includes/_tabbedinterface.scss for single property rules https://github.com/wet-boew/wet-boew/pull/1152#issuecomment-13217205
- [ ] find out what the :after pseudo is used for and move instance to mixin.scss https://github.com/wet-boew/wet-boew/pull/1182#discussion_r2939928
- [ ] CSSLint "Warning - Outlines should only be modified using :focus" in util.css
- [ ] CSSLint " Warning - display:inline has no effect on floated elements (but may be used to fix the IE6 double-margin bug)."
- [ ] CSSLint: Warning - margin can't be used with display: inline.
- [x] Split #1233 and send in separate PRs with heads-up to cf for comments
- [ ] Change class extend in  src/base/sass/_default-ie.scss to placeholder

---

Done
- .opacity and .width classes to iterators
- enable SVG flag for gradients in IE9
- remove i18n\base.js after build
- remove src README
- move sample js template to wiki
- ensure text-shadow doesn't mixin
- verify placeholder naming in src/grids/sass/_responsive.scss https://github.com/wet-boew/wet-boew/pull/1151#issuecomment-13087412
- Tabbed Interface: remove opacity includes in IE sheet as the mixin in the main already emits progid values
- Move clip/hidden property to mixins.scss https://github.com/wet-boew/wet-boew/pull/1183#discussion_r2940038
- Turing on SVG showed multiple dup gradients
  - util.css https://travis-ci.org/wet-boew/wet-boew/builds/4662277/#L88
  - theme-gcwu-fegc/css/theme.css https://travis-ci.org/wet-boew/wet-boew/builds/4662277/#L414
  - theme-gcwu-intranet/css/theme.css https://travis-ci.org/wet-boew/wet-boew/builds/4662277/#L501
- Combine jQuery mobile CSS with theme-\* files using @imports
  - Update demos
  - Add as top import of each sheet
  - Update build and verify any base64 encoding issues
